### ISSUE TITLE
Fetch dependency paths using `cypm deps --language-server`

### ISSUE THREAD

**Issue by fwcd** [fwcd/curry-language-server#48]
Instead of trying to resolve CPM packages against `PACKAGE_INSTALL_PATH` from `cypm config` we should just use `cypm deps --language-server`, which exports a list of dependency paths to `.curry/language-server/paths.json`.

**Comment by fwcd** [comment]
Note: We may need to automatically perform a `cypm install` since, as opposed to `cypm deps`, `cypm deps -p` errors when the packages are not up to date.

**Comment by mihanus** [comment]
Good point. However, `cypm install` is anyway necessary to download the package sources, otherwise you can't have access to the sources in order to generate the ICurry files. Thus, a good strategy might to call `cypm deps -p` and, if this returns with exit code > 0, call `cypm install --noexec` to install all required packages. Afterwards, `cypm deps -p` should work to obtain the dependency paths so that the source programs can be compiled. Otherwise, the package has dependency conflicts.
